pipeline {
  agent any
  stages {
    stage('build step') {
       steps {
       script {
         def customImage = docker.build("my-image:${env.BUILD_ID}", "-f jenkins/Dockerfile .")
       }
      }
    } 
      stage('run step') {
       steps {
       script {
         docker.image("my-image:${env.BUILD_ID}").Run('-tid -p 80:80'){
       }
      }   
     }
   }
  }
}
