def remote = [:]
remote.name = "docker"
remote.host = "34.219.76.37"
remote.allowAnyHosts = true
pipeline {
  agent any
  stages {
    stage('build step') {
      steps {
        script {
          withCredentials([string(credentialsId: 'docker_user', variable: 'DOCKER_USER'),
                           string(credentialsId: 'docker_pass', variable: 'DOCKER_PASS')]){
          sh "echo ${DOCKER_PASS} | docker login --username ${DOCKER_USER} --password-stdin"
          docker.withRegistry("https://index.docker.io") {
            def customImage = docker.build("${DOCKER_USER}/my-image:${env.BUILD_ID}", "-f jenkins/Dockerfile .")
            customImage.push()
            customImage.push 'latest'
          }
                           }
        }
      }
    }
      stage('run step') {
       steps {
       script {
        withCredentials([sshUserPrivateKey(credentialsId: 'ssh_user', keyFileVariable: 'identity', passphraseVariable: '', usernameVariable: 'userName')]) {
        remote.user = userName
        remote.identityFile = identity
        sshCommand remote: remote, command: "docker run -tid -p 80:80 gevorg92/my-image:${env.BUILD_ID}"
        //  docker.image("my-image:${env.BUILD_ID}").withRun('-tid -p 80:80'){
        }
      }   
     }
   }
  }
}

